# Generated by Django 2.0.5 on 2018-11-29 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181111_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teetime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teetime_Name', models.CharField(default='Tee Time', max_length=50)),
                ('Teetime_Start', models.DateTimeField(default=django.utils.timezone.now)),
                ('Golf_Carts', models.IntegerField(default=0)),
                ('Equipment_Rentals', models.IntegerField(default=0)),
                ('Golfers_Allowed', models.IntegerField(default=1)),
                ('Created_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Updated_Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
